### ISSUE TITLE
Cannot generate route with addon installed

### ISSUE THREAD

**Issue by Bouke** [winding-lines/ember-cli-typify#4]
$ ember generate route invoice
    Cannot find module 'process'
    Error: Cannot find module 'process'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:278:25)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> ([...]/node_modules/ember-cli-typify/index.js:5:15)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)

**Comment by winding-lines** [comment]
@Bouke I cannot reproduce  this. Which version of node do you use?

```
$ ember generate route invoice
WARNING: Node v7.1.0 has currently not been tested against Ember CLI and may result in unexpected behaviour.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
installing route
  create app/routes/invoice.js
  create app/templates/invoice.hbs
updating router
  add route invoice
installing route-test
  create tests/unit/routes/invoice-test.js
```

**Comment by winding-lines** [comment]
We are deprecating this addon in favor of the pre-existing ember-cli-typescript. Do you mind switching to ember-cli-typescript and let me know if you still see this problem? Please file a new issue agains that addon if you do.

Thanks a lot of your patience and help to make the community better.

Marius
